CREATE TABLE `production_order_operation_data`
(
    `ProductionOrder`               varchar(20) NOT NULL,
    `ProductionRoutingGroup`        varchar(10) NOT NULL,
    `ProductionRouting`             varchar(20) NOT NULL,
    `ProductionRoutingIntVersion`   varchar(8) NOT NULL,
    `ProductionSequence`            varchar(6) NOT NULL,
    `OperationIntID`                varchar(8) NOT NULL,
    `ProductionOrderSequenceText`   varchar(20) DEFAULT NULL,
    `ProductionOrderCategory`       varchar(20) DEFAULT NULL,
    `ProductionOrderOperationText`  varchar(20) DEFAULT NULL,
    `OperationIsCreated`            tinyint(1) DEFAULT NULL,
    `OperationIsReleased`           tinyint(1) DEFAULT NULL,
    `OperationIsConfirmed`          tinyint(1) DEFAULT NULL,
    `OperationIsPartiallyConfirmed` tinyint(1) DEFAULT NULL,
    `OperationIsDeleted`            tinyint(1) DEFAULT NULL,
    `OperationIsTechlyCompleted`    tinyint(1) DEFAULT NULL,
    `OperationIsClosed`             tinyint(1) DEFAULT NULL,
    `OperationIsScheduled`          tinyint(1) DEFAULT NULL,
    `OperationIsPartiallyDelivered` tinyint(1) DEFAULT NULL,
    `OperationIsDelivered`          tinyint(1) DEFAULT NULL,
    `WorkCenterTypeCode`            varchar(6) DEFAULT NULL,
    `WorkCenter`                    varchar(20) DEFAULT NULL,
    `OpErlstSchedldExecStrtDte`     varchar(20) DEFAULT NULL,
    `OpErlstSchedldExecStrtTme`     varchar(20) DEFAULT NULL,
    `OpErlstSchedldExecEndDte`      varchar(20) DEFAULT NULL,
    `OpErlstSchedldExecEndTme`      varchar(20) DEFAULT NULL,
    `OpActualExecutionStartDate`    varchar(20) DEFAULT NULL,
    `OpActualExecutionStartTime`    varchar(20) DEFAULT NULL,
    `OpActualExecutionEndDate`      varchar(20) DEFAULT NULL,
    `OpActualExecutionEndTime`      varchar(20) DEFAULT NULL,
    `ErlstSchedldExecDurnInWorkdays` varchar(20) DEFAULT NULL,
    `OpActualExecutionDays`         varchar(20) DEFAULT NULL,
    `OperationUnit`                 varchar(20) DEFAULT NULL,
    `OpPlannedTotalQuantity`        varchar(20) DEFAULT NULL,
    `OpTotalConfirmedYieldQty`      varchar(20) DEFAULT NULL,
    `CreatedDateTime`               varchar(20) DEFAULT NULL,
    `LastModifiedDateTime`          varchar(20) DEFAULT NULL,
    PRIMARY KEY (`ProductionOrder`, `ProductionRoutingGroup`, `ProductionRouting`, `ProductionRoutingIntVersion`, `ProductionSequence`, `OperationIntID`),
    CONSTRAINT `ProductionOrderOperationData_fk` FOREIGN KEY (`ProductionOrder`) REFERENCES `production_order_general_data` (`ProductionOrder`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
