CREATE TABLE `production_order_component_data`
(
  `ProductionOrder`                  varchar(20) NOT NULL,
  `ProductionOrderSequence`          varchar(20) NOT NULL,
  `ProductionOrderOperation`         varchar(20) NOT NULL,
  `BOMItem`                          varchar(20) NOT NULL,
  `Reservation`                      varchar(20) DEFAULT NULL,
  `ReservationItem`                  varchar(20) DEFAULT NULL,
  `SpaceProductGroup`                varchar(20) DEFAULT NULL,
  `SpaceProduct`                     varchar(20) DEFAULT NULL,
  `ProductionBaseCamp`               varchar(20) DEFAULT NULL,
  `ComponentRequirementDate`         varchar(20) DEFAULT NULL,
  `ComponentRequirementTime`         varchar(20) DEFAULT NULL,
  `ReservationIsFinallyIssued`       tinyint(1) DEFAULT NULL,
  `ComponentIsMarkedForBackflush`    tinyint(1) DEFAULT NULL,
  `SortField`                        varchar(10) DEFAULT NULL,
  `BillOfMaterialCategory`           varchar(20) DEFAULT NULL,
  `BOMItemCategory`                  varchar(20) DEFAULT NULL,
  `BillOfMaterialItemNumber`         varchar(20) DEFAULT NULL,
  `BOMItemDescription`               varchar(20) DEFAULT NULL,
  `BaseCampStorageLocation`          varchar(20) DEFAULT NULL,
  `Batch`                            varchar(20) DEFAULT NULL,
  `SupplyArea`                       varchar(20) DEFAULT NULL,
  `GoodsRecipientName`               varchar(20) DEFAULT NULL,
  `UnloadingPointName`               varchar(20) DEFAULT NULL,
  `ComponentIsAlternativeItem`       tinyint(1) DEFAULT NULL,
  `AlternativeItemGroup`             varchar(20) DEFAULT NULL,
  `AlternativeItemStrategy`          varchar(20) DEFAULT NULL,
  `AlternativeItemPriority`          varchar(20) DEFAULT NULL,
  `UsageProbabilityPercent`          varchar(20) DEFAULT NULL,
  `QuantityIsFixed`                  tinyint(20) DEFAULT NULL,
  `ComponentScrapInPercent`          varchar(20) DEFAULT NULL,
  `OperationScrapInPercent`          varchar(20) DEFAULT NULL,
  `BaseUnit`                         varchar(5) DEFAULT NULL,
  `RequiredQuantity`                 varchar(20) DEFAULT NULL,
  `WithdrawnQuantity`                varchar(20) DEFAULT NULL,
  `ConfirmedAvailableQuantity`       varchar(20) DEFAULT NULL,
  `ComponentOriginalQuantity`        varchar(20) DEFAULT NULL,
    PRIMARY KEY (`ProductionOrder`, `ProductionOrderSequence`, `ProductionOrderOperation`, `BOMItem`),
    CONSTRAINT `ProductionOrderComponentData_fk` FOREIGN KEY (`ProductionOrder`) REFERENCES `production_order_general_data` (`ProductionOrder`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
